config.dev.json
Use [devnet notion page](https://www.notion.so/chainsafe/Dev-environment-756afefdd5b848fc854dea75af9f8133) to double-check.
=> Add resources to devnet configuration

README.md, config.test.json
Expand testnet configuration with resources.
=> Add resources to testnet config

config.dev.json
Updates addresses of ERC20Handlers - handlers now implement different decimals value.
=> Update ERC20Handlers addresses

config.dev.json
=> feat: add Sepolia support on devnet

.gitignore, config.test.json
Add config for Sepolia on testnet
=> feat: add sepolia support for testnet

config.dev.json, config.test.json
- Add Rococo phala to devnet config file
=> feat: Add domain 5 for rococo phala on devnet

config.dev.json, config.test.json
Add balance-checker deployment infor
added burnable property
added substrate dev info
Related to: https://github.com/sygmaprotocol/balance-checker/issues/16
=> feat: Add balance-checker deployment info

config.test.json
- remove LR token from rhala
- added chain ID to testnet configuration
- added GPHA token on Goerli
=> Fix testnet config

config.test.json
- change decimals for PHA token to 12 inside Rhala domain
- add chain id for Rhala
=> Update testnet configuration

testnet/shared-config-dev.json
Update address to target the latest version of PGH
=> Migrate to latest version of pgh

mainnet/shared-config-mainnet.json, testnet/shared-config-test.json
fix:
- set nativeTokenDecimals to 12 (PHA)
- remove assetID for native resource
=> fix: fix native decimal places

testnet/balance-config-test.json, testnet/shared-config-test.json
- Update Sepolia configuration based on new contract deployment
- Update Base configuration based on new contract deployment
- Add Cronos configuration based on contract deployment
- Add Phala relayer address on all networks
- Add Cronos to monitoring
- Fix base configuration
=> Add base and cronos to testnet

README.md, schema.json
Extending schema file with additional regex or enum validations.
closes #2
=> feat: Added more validations

mainnet/shared-config-mainnet.json, testnet/shared-config-test.json
Changes decimals for 18 on GMP resources
=> feat: decimal value for GMP

mainnet/shared-config-mainnet.json
- Replace current feeRouter with new feeRouter that has whitelisting feature
- Replace basicFeeHandlers with new basicFeeHandler
=> chore: replace fee router and basic fee handler

schema.json, testnet/shared-config-dev.json, testnet/shared-config-test.json
Add erc721 to sepolia and cronos
=> chore: add erc721

testnet/shared-config-test.json
It will be used mostly for cross-chain contract deployment
=> chore: add new gmp handlers (with increeesed maxFee limit) + new gmp resource

testnet/shared-config-test.json
Upgraded feeHandlers to new version
=> chore: change feeHandler addresses

testnet/balance-config-test.json
=> Add spectre addresses

testnet/balance-config-test.json, testnet/shared-config-test.json
- add amoy network
- remove mumbai from balance-checker config
- add sygUSD to base_sepolia balance-checker config
=> chore: add amoy network

testnet/shared-config-dev.json
- removed resources
- removed networks
- left just sepolia and holesky
- deployed new feeHandler contracts
=> chore: update devnet environment

testnet/shared-config-dev.json
redeploy new devnet environment (fixing keyshare issue)
=> chore: redeploy devnet

schema.json, testnet/shared-config-test.json
Add Tangle standalone chain testnet
=> chore: Add tangle testnet in testnet shared config

testnet/shared-config-test.json
=> chore: add tangle token

testnet/balance-config-test.json
Added Bison and B3-Sepolia networks to balance-config. 
Also, added relayers 30,31 and 40 to all networks in balance-config.
=> chore: Add bison, b3 networks and new relayers to balance config

testnet/shared-config-test.json
Add new erc20 extended erc20 handler
=> chore: add new erc20 handler

testnet/shared-config-test.json
- [New ERC20 Handler](https://sepolia.etherscan.io/address/0xFFFFAa3fE6df9a5Fcb31855004B734b5749e7D2F#code)
- [New TWAP ERC20 Fee Handler](https://sepolia.etherscan.io/address/0x0e5F28d6874938CF1504Fe65Fa491E1BA7891B6A)
- [DefaultMessageReceiver](https://sepolia.etherscan.io/address/0x1fb4751c921bC764EfBca19b1312806B5BD8DdA1)
- [Register ERC20 handler TX](https://sepolia.etherscan.io/tx/0xa680fd24cc9646f8a21debd3e2792cc2c181f4f03d99c26f83545b80732ea1cd)
- [Register fee handler -> Base Sepolia](https://sepolia.etherscan.io/tx/0x9ab78f3079043c88603d6a57526277ffdbc1b75a0530907754c0e2fca31f3e5f)
- [Register fee handler -> B3 Sepolia](https://sepolia.etherscan.io/tx/0x31d9cb343dc7f17254927b162f1fa5cf0548766a651a699f7347aaf1e863e3e1)
- [Register ERC20 handler …
=> chore: update erc20 handlers

testnet/shared-config-test.json
[NativeTokenAdapter](https://sepolia.etherscan.io/address/0xb55d0f87ee4a76faa2f1d01a5abf3f1eb1bbfdd6#code)
[NativeTokenHandler](https://sepolia.etherscan.io/address/0x2a71bc0efcbcFd3789385F8E49baf558b73904F8#code)
[Grant HANDLER_ROLE to Native Handler on DefaultMessageReciever](https://sepolia.etherscan.io/tx/0x16759a88b8a5de111b301381f52638aa1776d40067d4880938c750c7c9d5cc59)
[Bridge.adminSetResource for ETH](https://sepolia.etherscan.io/tx/0x06d4658c6bc0478637b553012a8db1cccc89142dc002ea56b49cca1bbff075a2)
[Register route -> BaseSepolia for ETH](https://sepolia.etherscan.io/tx/0x5c0ff11bbe6e3e6c28f8b9ee45d9bb39ee011728e6f6f15b9afb2459a4b3c0d1)
[Register route -> B3Sepolia for ETH](https://sepolia.etherscan.io/tx/0x74ce06b3bfa865937deadc1952503bdb3fa69bdf36b09027e74672ca87ed3cd3)
--- …
=> chore: add native routes on testnet

mainnet/shared-config-mainnet.json
Homologates mainnet shared config with testnet and devent adding the caipIds
=> chore: caipId and caip19 for mainnet shared config

mainnet/balance-config-mainnet.json
- update the format of balance checker config
- add b3, optimism, arbitrum networks
- add a new topic for nativeTokenHandler balance check
=> chore: add updated balance-checker config

mainnet/balance-config-mainnet.json
- reduce minBalance for usdc
- remove liquidity monitoring from b3
=> chore: update minBalance for usdc
